version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./env.prod
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    depends_on:
      - db
      - redis_broker

  daphne:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: daphne -b 0.0.0.0 -p 8001  core.asgi:application  
    expose:
      - 8000
    env_file:
      - ./env.prod
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    depends_on:
      - db
      - redis_broker

  

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env.prod.db
 
      

  redis_broker:
    image: redis:7.0.4
    ports:
      - 6379:6379
    
    volumes:
      - redis_cache:/var/lib/redis/data/
  
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media


  

volumes:
  postgres_data:
  redis_cache:
  static_volume:
  media_volume:


